version: 2

sources: 
  - name: raw 
    schema: gz_raw_data
    description: Raw Data GZ
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: details about sales
        tests:
          - unique:
              column_name: "(orders_id|| '_' ||pdt_id )"
        columns:
          - name: date_date
            description: the date of sales
          - name: orders_id
            description: the orders id of sales
          - name: pdt_id
            description: the product id
          - name: revenue
            description: the revenue for sales
          - name: quantity
            description: the quantity for sales     

      - name: product
        identifier: raw_gz_product
        description: details about products
        columns:
          - name: products_id
            description: The primary key of the table
            tests:
              - not_null
              - unique
          - name: purchase_price
            description: the price for purchase
          
      - name: ship
        identifier: raw_gz_ship
        description: details about ship
        columns:
          - name: orders_id
            description: the orders id of sales, the primary key and foreign key
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: the fee of shipping
          - name: logCost
            description: the cost for logistic
          - name: ship_cost
            description: the cost for shipping

      - name: adwords
        identifier: raw_gz_adwords
        description: detail of campaign in adwords
        columns: 
          - name: campaign_key
            description: The primary key of the table
            tests:
              - not_null
              
      - name: bing
        identifier: raw_gz_bing
        description: detail of campaign in bing
        columns: 
          - name: campaign_key
            description: The primary key of the table
            tests:
              - not_null
              
              
      - name: criteo
        identifier: raw_gz_criteo
        description: detail of campaign in criteo
        columns: 
          - name: campaign_key
            description: The primary key of the table
            tests:
              - not_null
              
      - name: facebook
        identifier: raw_gz_facebook
        description: detail of campaign in facebook
        columns: 
          - name: campaign_key
            description: The primary key of the table
            tests:
              - not_null
              
      
      - name: int_sales_margin
        identifier: int_sales_margin
        description: deail of margin for sales

      - name: int_orders_operational
        identifier: int_orders_operational
        description: detail of operational for orders

      - name: int_oreders_maring
        identifier: int_orders_margin
        description: detail of margin for orders

      - name: int_campaigns
        identifier: int_campaigns
        description: detail of all campaigns

      - name: int_campaigns_day
        identifier: int_campaigns_day
        description: deatil of campaigns for day
      
      - name: int_campaigns_month
        identifier: int_campaigns_month
        description: deatil of campaigns for day

    



      